### ISSUE TITLE
Feature request/Implementation guideline to fetch a list from SingleItemContentProviderStore

### ISSUE THREAD

**Issue by droidekas** [reark/reark#139]
I am trying to use this pattern for a sample app. I need to implement an API which returns a list of objects.Where I am stuck is how to leverage the `SingleItemContentProviderStore` in that case.Because this works based on an id identifier.Any ideas?

EDIT : I can use `getStream()` , however this too would return individual item observables,however this still wont work well with a ListView,RecyclerView

**Comment by apoi** [comment]
The example GitHub app shows how you could do this. The app implements two data stores, GitHubRepositoryStore where each entry represents a single GitHub repository, and GitHubRepositorySearchStore where entries represent lists of repositories. Both of these stores extend the SingleItemContentProviderStore. You'll likely want to check out this structure.

In short, the sample app has an additional GitHubRepositorySearch POJO that contains results of an individual search (a list of repository ids), and GitHubRepositorySearchStore is a store for keeping these lists. Here the id used for storing different search result listings in the store is the search string.

**Comment by droidekas** [comment]
Correct me if I am wrong here:

`GitHubRepositorySearch` is a searchstring and a list of Ids which map to individual `GithubRepository` from the `GitHubRepositoryStore `. So effectively the `GithubRespositoyStore` always returns single objects. A related issue could be #30 

However I could not find the method that you mentioned there too. Still looking into this,any help provided would be really great :) .

**Comment by apoi** [comment]
Yes, `GitHubRepositoryStore` it's a store for single objects. The listing of API results should be stored in a second store, in this case `GitHubRepositorySearchStore` which stores the `GitHubRepositorySearch` object containing the list of element that the API returned.

The idea here is to keep object listing separate from the objects themselves. This is very useful for multiple reasons; for example two different API calls may result with the same items, and this way we can still store each item just once.

**Comment by droidekas** [comment]
Yes that is what is mentioned in the ReadMe too,and this is the ideal way to design it.However say in the current sample app,I need to display a list of all local repositories from`GitHubRepositoryStore`, How would I go about that?

**Comment by apoi** [comment]
For getting all the contents in a store you could use them method `Observable<List<T>> get(@NonNull U id)` from `SingleItemContentProviderStore` with empty id if your store's id type can be empty (e.g. a String). In this case the id is Integer that can't be empty though, so I'd add a new method to `GitHubRepositoryStore`:

    @NonNull
    public Observable<List<GitHubRepository>> getAll() {
        return get(GitHubProvider.GitHubRepositories.GITHUB_REPOSITORIES);
    }

This is a call to `Observable<List<T>> get(Uri uri)` from `ContentProviderStore` with the generic table Uri from the provider definition as an argument.

Alternatively you could use the ContentResolver directly in the method, with `getContentResolver().query()`. This allows you to add an actual criteria for the query as long as the data table has fields that can be queried. In the GitHub app example we just have the JSON blob, but one example of this can be seen in a store implemented [in a different project](https://github.com/apoi/quickbeer-next/blob/0c0217246f6f4d43e787fb164969ea59a0f2d7c8/app/src/main/java/quickbeer/android/next/data/store/BeerStore.java#L69).

**Comment by droidekas** [comment]
Will this be included in the `SingleItemContentProviderStore` , Right now I am using a constant to indicate an all query and have overriden as

```
 @NonNull
    @Override
    public Uri getUriForId(@NonNull Integer id) {
        Preconditions.checkNotNull(id, "Id cannot be null.");
        if (id != GET_ALL)
            return GitHubProvider.GitHubRepositories.withId(id);
        else
            return GitHubProvider.GitHubRepositories.GITHUB_REPOSITORIES;
    }
```

But your method seems much more sense. Thank you for the other example! ,that will be really useful .

**Comment by apoi** [comment]
I think it's best implemented in the actual stores instead of `SingleItemContentProviderStore`, as it's likely that the store would like to filter or sort that somehow, for example just as shown in that other project. Perhaps it would be good to add a more complex example that showcases how to do things like this though.

As a side note, we'll soon be changing a bit the way stores are structured (at PR https://github.com/reark/reark/pull/135), mostly to make it nicer to also implement stores backed with something else than the ContentProvider. You may want to check that out too.

**Comment by droidekas** [comment]
Sure will do so. Closing the issue since my problem was solved. Thanks a lot!

**Comment by droidekas** [comment]
Would it be possible to return an incomplete observable instead . i.e. use `getStream(Uri uri)` instead of `get(Uri uri)`
