### ISSUE TITLE
Default groupOperations() from ContentProviderStoreCoreBase doesn't buffer last emitted item

### ISSUE THREAD

**Issue by bifri** [reark/reark#162]
Default groupOperations() from io.reark.reark.data.stores.cores.ContentProviderStoreCoreBase doesn't buffer last emitted item if 
`groupMaxSize == total number of items emitted by source observable so far`
[stackoverflow](http://stackoverflow.com/questions/43709249/rxjava-last-item-is-not-emitted-while-using-publish-debounce-buffer-sk)

By the way are these changes reasonable to avoid possible multi-threading problems?
```
@NonNull
private final Subject<CoreValue<U>, CoreValue<U>> operationSubject =
        PublishSubject.<CoreValue<U>>create().toSerialized();

private AtomicInteger nextOperationIndex = new AtomicInteger(0);

completionNotifiers.put(index, PublishSubject.<Boolean>create().toSerialized());

```

**Comment by apoi** [comment]
Thanks for the report, I can indeed reproduce this.

As for the multi-threading problems, could you try if #160 fixes your issues?

**Comment by apoi** [comment]
The same grouping logic can be expressed also with `Observable.window()`:

    @NonNull
    protected <R> Observable<List<R>> groupOperations(@NonNull final Observable<R> source) {
        return source.publish(stream -> {

            Observable<R> boundary = Observable.amb(
                        stream.debounce(groupingTimeout, TimeUnit.MILLISECONDS),
                        stream.skip(groupMaxSize - 1))
                    .first() // Complete observable after the first reached trigger
                    .repeatWhen(observable -> observable);  // Resubscribe immediately for the next buffer

            // Window
            return Observable.switchOnNext(stream.window(boundary).map(Observable::toList));

            // Buffer
            // return stream.buffer(boundary);

        });
    }

Interestingly, this gives the very same behaviour. I'm a bit baffled at what's causing this.
