### ISSUE TITLE
The service does not get shutdown after incoming requests have been handled

### ISSUE THREAD

**Issue by about-midnight** [reark/reark#62]
The service is idling and could use [stopSelf](http://developer.android.com/reference/android/app/Service.html#stopSelf())

**Comment by tehmou** [comment]
A good idea. Right now there is no way of finding out if there is a request ongoing, so this would first require a way to identify if any fetcher is active. It should not be too difficult, though probably needs a more formalised way of keeping track of them.

**Comment by apoi** [comment]
After #121 the service won't stay open after the main app has closed. I think this covers the issue, so closing.
